name: CI
on:
  push:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: "1.8.2"
      - name: Install dev dependencies (lint)
        run: poetry install -v --no-interaction --no-root --only dev
      - name: Run linting
        run: |
          poetry run isort src
          poetry run ruff check src --fix
          poetry run ruff format src